apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.service.expose: flask-ex
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: web:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: flask-ex
      uri: https://github.com/mikespub-org/sclorg-django-ex.git
    type: ""
  strategy:
    dockerStrategy: {}
    type: ""
  triggers:
    - type: ConfigChange
status:
  lastVersion: 0
