version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: flask-ex

- package-ecosystem: "docker" # See documentation for possible values
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: flask-ex

- package-ecosystem: "github-actions" # See documentation for possible values
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: flask-ex
