FROM registry.access.redhat.com/ubi9/python-311

# Add application sources with correct permissions for OpenShift
USER 0
# ADD app-src .
ADD requirements.txt ./requirements.txt
ADD app/ ./app
ADD tests/ ./tests
ADD migrations/ ./migrations
ADD wsgi.py ./wsgi.py
ADD conf/ ./conf
RUN chown -R 1001:0 ./
USER 1001

# Install the dependencies
RUN pip install -U "pip>=23.2.1" && \
    pip install -r requirements.txt

# Run the application
CMD ["gunicorn", "-b", "0.0.0.0:8080", "wsgi:application"]
