apiVersion: v1
kind: Secret
metadata:
  labels:
    app: webapp
    template: webapp
  name: {{ .Values.name }}
stringData:
  app-secret-key: {{ .Values.app_secret_key }}
  database-password: ${APP_DB_PASS}
  database-user: ${APP_DB_USER}
