apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.app_db_service_name }}",
      "kind": "Service"}]'
  labels:
    app: webapp
    template: webapp
  name: {{ .Values.name }}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: {{ .Values.name }}
