apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
  labels:
    template: robot-template
  name: sa-token-{{ .Values.name }}
type: kubernetes.io/service-account-token
