name: openshift/charts/kompose
description: A generated Helm Chart for openshift/charts/kompose from Skippbox Kompose
version: 0.0.1
apiVersion: v1
keywords:
  - openshift/charts/kompose
sources:
home:
