name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mikespuborg/sclorg-flask-ex:$(date +%s)
